# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TiszaToTajmetria
                                 A QGIS plugin
 Landscape-based analysis of the mosaicity of Lake Tisza
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-24
        copyright            : (C) 2025 by Tasnádi Attila
        email                : tasnadi.attila21@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TiszaToTajmetria class from file TiszaToTajmetria.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tisza_to_tajmetria import TiszaToTajmetria
    return TiszaToTajmetria(iface)
